# ------------------------------------------------------------------------
# Copyright (c) 2021 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: LG_HINet_Crop512_Step384

model_type: ImageRestorationModel
scale: 1
num_gpu: 2  # set num_gpu: 0 for cpu mode
manual_seed: 37127 # Gwangya coordinate

# dataset and data loader settings
datasets:
  train:
    name: SIDD
    type: PairedImageDataset_SIDD
    dataroot_gt: [~~~root_path~~~]/datasets/train/gt_crops
    dataroot_lq: [~~~root_path~~~]/datasets/train/input_crops

    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 512
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: SIDD_val
    type: PairedImageDataset_SIDD
    dataroot_gt: [~~~root_path~~~]/datasets/val/gt_crops
    dataroot_lq: [~~~root_path~~~]/datasets/val/input_crops
    io_backend:
      type: disk

# network structures
network_g:
  type: HINet
  wf: 32
  hin_position_left: 0
  hin_position_right: 4


# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~
# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
 #   weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: TrueCosineAnnealingLR
    #T_max: 400000
    T_max: 200000
    eta_min: !!float 1e-6
    #last_epoch: 179

  #total_iter: 400000
  #total_iter: 4000
  total_iter: 200000
  warmup_iter: -1 # no warm up
  use_grad_clip: true
  # losses
  #type: L1Loss
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1
    reduction: mean
#    toY: true

# validation settings
val:
#  val_freq: 10
#  val_freq: !!float 2.5e4
  val_freq: !!float 2e3
  save_img: false
#  grids: true
#  crop_size: 256
  rgb2bgr: true
  use_image: false
  max_minibatch: 16
  #max_minibatch: 1

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false
# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
